---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-prom-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-prom-app
  template:
    metadata:
      labels:
        app: demo-prom-app
    spec:
      containers:
      - name: app
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: demo-prom-app
  labels:
    app: demo-prom-app
spec:
  selector:
    app: demo-prom-app
  ports:
  - name: web
    port: 8080