version: '2'
services:
  db:
    image: mariadb:5
    volumes:
      ##
      # Ajouter le montage d'un volume pour la persistance des données MariaDB (répertoire /var/lib/mysql)
      ##
    restart: always
    environment:
      ##
      # Ajouer les variables d'environnement concernant les credentials pour MariaDB
      ##
  dbadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      ##
      # Ajouer les variables d'environnement concernant les credentials pour MariaDB
      ##
    links:
      ##
      # Ajouer la dépendance necessaire
      ##

  wordpress:
    image: wordpress:latest
    links:
      ##
      # Ajouer les dépendance necessaires (mariadb + phpmyadmin)
      ##
    ports:
      - "8000:80"
    restart: always
    environment:
      ##
      # Ajouer les variables d'environnement pour que WordPress puisse se connecter à MariaDB
      ##
